spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oldmarket?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  ###QQ邮箱配置
  mail:
    host: smtp.qq.com
    username: 574154759@qq.com
    password: digwwuuopvxmbegf
    properties.mail.smtp.port: 465
    from: 574154759@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


